### ISSUE TITLE
Create a swap page for REB2 users

### ISSUE THREAD

**Issue by brymut** [Ditto-money/swap-frontend#15]
Copied from website repo # 10 by @chefchansey 

Users of the token REB2 token will get an instance of the DittoSwap contract where they can swap REB2 for DITTO at an 1:1 rate. Create a copy of the vampire swap frontend and deploy to: https://ditto.money/reb2swap

Make the following changes:

Change page title to "DITTO redemption for REB2 users"
Remove the "total DITTO left" and "DITTO remaining for user" labels
The smart contract ABI is unchanged. The smart contract for this swap is already deployed and configure at:

https://etherscan.io/address/0xC621C5dc44Eb12cacEBd5959E07D8FeC508f868E

**Comment by chefchansey** [comment]
Is there something to review yet?

**Comment by brymut** [comment]
Yes, sent the review link on Telegram yesterday. Here it is, forgot to post here too https://swap-ui-git-reb2-bryanmutai.vercel.app/

**Comment by chefchansey** [comment]
Looks fine to me!
